service: bitbucket-automation

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 1024

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: false
      - http:
          path: /{proxy+}
          method: ANY
          cors: false

plugins:
  - serverless-offline
